GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjE1ZDVlMDQwZTQ4ZWM1MzdmOGI2YjgiLCJmaXJzdF9uYW1lIjoiSmlkdWwiLCJsYXN0X25hbWUiOiJJc2xhbSIsImVtYWlsIjoiamFpZHVsMjZAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMi0wMi0yM1QwNjozNjoxNi40MTZaIiwidXBkYXRlZEF0IjoiMjAyMi0wMi0yM1QwNjozNjoxNi40MTZaIiwiX192IjowLCJpYXQiOjE2NDU2ODYyMzQsImV4cCI6MTY0NTY4NjI2NH0.Cpjl2Is9MjlhyHEMyaB2zZ_QUw_mMUA1WRy4Itmhq-M

###

POST http://localhost:3001/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjE1ZDVlMDQwZTQ4ZWM1MzdmOGI2YjgiLCJmaXJzdF9uYW1lIjoiSmlkdWwiLCJsYXN0X25hbWUiOiJJc2xhbSIsImVtYWlsIjoiamFpZHVsMjZAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMi0wMi0yM1QwNjozNjoxNi40MTZaIiwidXBkYXRlZEF0IjoiMjAyMi0wMi0yM1QwNjozNjoxNi40MTZaIiwiX192IjowLCJpYXQiOjE2NDU2ODYyMzR9.UQoNkJSDSQc9mCWOtteLjG265Pe3GtHZeTxcUJw7IH0"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "jaidul26@gmail.com",
    "password": "123456"
}
