GET http://localhost:3001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjE1ZDVlMDQwZTQ4ZWM1MzdmOGI2YjgiLCJmaXJzdF9uYW1lIjoiSmlkdWwiLCJsYXN0X25hbWUiOiJJc2xhbSIsImVtYWlsIjoiamFpZHVsMjZAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMi0wMi0yM1QwNjozNjoxNi40MTZaIiwidXBkYXRlZEF0IjoiMjAyMi0wMi0yM1QwNjozNjoxNi40MTZaIiwiX192IjowLCJpYXQiOjE2NDU3NjkxMDEsImV4cCI6MTY0NTc2OTEzMX0.Bi7NoBdB0DucDaeRnMGK6vQqZbdiICm_L7wkFo-POcw

###

POST http://localhost:3001/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjE1ZDVlMDQwZTQ4ZWM1MzdmOGI2YjgiLCJmaXJzdF9uYW1lIjoiSmlkdWwiLCJsYXN0X25hbWUiOiJJc2xhbSIsImVtYWlsIjoiamFpZHVsMjZAZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMi0wMi0yM1QwNjozNjoxNi40MTZaIiwidXBkYXRlZEF0IjoiMjAyMi0wMi0yM1QwNjozNjoxNi40MTZaIiwiX192IjowLCJpYXQiOjE2NDU3NjkwODV9.9_ixUAQosDFwTWC12q_x21IxZqP4VDiWnajxtpfFuSE"
}

###

POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "jaidul26@gmail.com",
    "password": "123456"
}
