// import chai from "chai" 
import app from "../../server.test"
import request from "supertest"
import assert from "assert"

describe("AUTH API", () => {
    const payload = {
        "first_name": "Sidul",
        "last_name": "Islam",
        "email": "rahaddiu@gmail.com",
        "password": "123456"
    }

    it("It should REGISTER a user", (done) => {
        request(app)
        .post("/register")
        .send(payload)
        .set('Accept', 'application/json')
        .expect('Content-Type', /json/)
        .expect(201)
        .end(function(err, res) {
            if (err) return done(err);
            assert(res.body.first_name, payload.first_name)
            assert(res.body.last_name, payload.last_name)
            assert(res.body.email, payload.email)
            return done();
        })
        
    })

    let refreshToken: string = ""

    it("It should LOGIN a user", (done) => {
        request(app)
        .post("/login")
        .send({email: payload.email, password: payload.password})
        .set('Accept', 'application/json')
        .expect('Content-Type', /json/)
        .expect(200)
        .end((err, res) => {
            if (err) return done(err)
            assert(typeof(res.body.accessToken), "string")
            assert(typeof(res.body.refreshToken), "string")
            assert(typeof(res.body.expiresIn), "string")
            refreshToken = res.body.refreshToken
            return done();
        })
    })

    let accessToken: string = ""
    it("It should get TOKEN using refresh token", (done) => {
        request(app)
        .post("/token")
        .send({token: refreshToken})
        .set('Accept', 'application/json')
        .expect('Content-Type', /json/)
        .expect(200)
        .end((err, res) => {
            if (err) return done(err)
            assert(typeof(res.body.accessToken), "string")
            assert(typeof(res.body.expiresIn), "string")
            accessToken = res.body.accessToken
            return done();
        })
    })

    it("It should use ACCESS TOKEN generated by REFRESH TOKEN for user endpoint", (done) => {
        request(app)
        .get("/users")
        .set('Authorization', `Bearer ${accessToken}`)
        .expect('Content-Type', /json/)
        .expect(200)
        .end((err, res) => {
            if (err) return done(err)
            return done();
        })
    })

})